name: Check PR Approval by MGVega

on:
  pull_request:
    branches: [ "main" ]
    #types: [opened, synchronize, reopened, review_requested, review]

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar aprobación de MGVega
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            const approvedByMGVega = reviews.some(review =>
              review.user.login === 'MGVega' && review.state === 'APPROVED'
            );
            if (!approvedByMGVega) {
              core.setFailed('Este PR necesita la aprobación de MGVega.');
            }
